name: ReSharper Inspect Code
run-name: ReSharper Inspect Code
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2
      - name: Set up Unity
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.38f1
          targetPlatform: Android
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
      - name: InspectCode
        uses: JetBrains/ReSharper-InspectCode@v0.8
        with:
          solution: ./android-photo-picker.sln
          eXtensions: JetBrains.Unity
          verbosity: INFO
          debug: true
    permissions:
      security-events: write
